name: Deliveroo CI/CD Pipeline

on:
  push:
    branches: [main, Development]
  pull_request:
    branches: [main, Development]

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend Build
    defaults:
      run:
        working-directory: ./Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Backend dependencies
        run: |
          cd Backend
          pip install -r requirements.txt

      - name: (Optional) Backend Linting/Build Step
        run: echo "Backend setup complete"

  frontend:
    runs-on: ubuntu-latest
    name: Frontend Build
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  deploy:
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy (Render + Vercel)

    steps:
      - name: Trigger external deploy
        run: echo "Code merged to main. Render and Vercel will auto-deploy from GitHub connection."